# Generated by Django 3.2.16 on 2023-01-21 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('zipcode', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='college',
            name='city',
        ),
        migrations.RemoveField(
            model_name='college',
            name='email',
        ),
        migrations.RemoveField(
            model_name='college',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='college',
            name='state',
        ),
        migrations.AddField(
            model_name='college',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.location'),
        ),
    ]
