# Generated by Django 3.2.16 on 2023-01-22 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230121_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('abbreviation', models.CharField(max_length=2, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='college',
            name='address',
        ),
        migrations.RemoveField(
            model_name='college',
            name='location',
        ),
        migrations.RemoveField(
            model_name='college',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='college',
            name='website',
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.state'),
        ),
        migrations.AddField(
            model_name='college',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.city'),
        ),
    ]
