# Generated by Django 4.1.5 on 2023-02-26 10:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_employee_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=multiselectfield.db.fields.MultiSelectField(max_length=32, null=True),
        ),
    ]
