# Generated by Django 4.1.5 on 2023-01-27 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230122_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='abbreviation',
        ),
    ]
