# Generated by Django 3.2.18 on 2023-03-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_employee_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='category',
            field=models.CharField(choices=[('IIT', 'IIT'), ('NIT', 'NIT'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='courses',
            field=models.CharField(choices=[('BTech', 'BTech'), ('MTech', 'MTech'), ('MS', 'MS'), ('MBA', 'MBA')], max_length=10, null=True),
        ),
    ]
