# Generated by Django 4.1.5 on 2023-02-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_city_name_remove_state_name_city_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='website',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
