# Generated by Django 4.1.5 on 2023-03-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20230303_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegeid', models.IntegerField(max_length=100, null=True)),
                ('date', models.CharField(max_length=100, null=True)),
                ('time', models.CharField(max_length=100, null=True)),
                ('message', models.CharField(max_length=512, null=True)),
            ],
        ),
    ]
