# Generated by Django 4.1.5 on 2023-03-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_followup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='collegeid',
            field=models.IntegerField(null=True),
        ),
    ]
