# Generated by Django 4.1.5 on 2023-03-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_followup_collegeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='aadhar',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='fathername',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
