# Generated by Django 4.1.5 on 2023-05-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_employee_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='employee',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
