# Generated by Django 4.1.5 on 2023-06-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_followup_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='status',
            field=models.CharField(default='active', max_length=12),
        ),
    ]
